<?php $proxima_pag = 2; ?>
<?php  if(isset($_GET['pag'])){
	    $proxima_pag = $_GET['pag'] + 1;
     } 
?>

<div class=" text-center p-3">
   <a class="btn btn-dark" href="/estudar">Estudar Agora!!</a>
   
</div>
<div class="text-center">
 <?php $_GET['pag'] = !isset($_GET['pag']) ? 1 : $_GET['pag']; ?>
 <?php if(($this->tot['tot'] - ($_GET['pag'] * 10)) > 10){ ?>
      <a class="text-dark text-right container" href="/entrada?pag=<?=$proxima_pag?>">
          Próxima página
      </a>
   <?php } ?>
   Total de registros: <?= $this->tot['tot'] ?>
</div>



<?php foreach($this->parametro as $key => $registro){?>
   <section class="container p-3">
   	  <div class="center">
   	  	 <h5><?= $registro['nome']?> Registro: </h5>
   	  	 <p>Estudou <?= $registro['horas_atuais']?> na data <?= $registro['data'] ?></p>
   	  	 <p>Horas totais estudadas de <?= $registro['nome']?>: <?= $registro['horas_totais'] ?> : <?= $registro['minutos_totais'] ?> : <?= $registro['segundos_totais'] ?></p>
   	  	 <p class="text-danger">Obs: <?= $registro['anotacoes'] ?></p>
   	  </div>
   </section>
<?php } ?>




