<div class=" text-center p-3">
<a class="btn btn-dark" href="/estudar">Estudar Agora!!</a>
</div>
<?php foreach($this->parametro as $key => $value){?>
   <section class="container p-3">
   	  <div class="center">
   	  	 <h5><?= $value['nome']?> Registro: </h5>
   	  	 <p>Estudou <?= $value['horas_atuais']?> na data <?= $value['data'] ?></p>
   	  	 <p>Horas totais estudadas de <?= $value['nome']?>: <?= $value['horas_totais'] ?></p>
   	  	 <p class="text-danger">Obs: <?= $value['anotacoes'] ?></p>
   	  </div>
   </section>
<?php } ?>
