
<div class="container">
	<div class="center p-4">
		<div class="text-center">
			<h2 class="p-3" id="contador">00:00:00</h2>
			<div class="row">
				 <button class="btn btn-primary col-md-4" id="comecar" onclick="iniciar_cronometro()">Começar</button>
				 <button class="btn btn-primary col-md-4" id="pausar" onclick="pause()">Pausar</button>
				 <button class="btn btn-primary col-md-4" id="continuar">Continuar</button>
			</div>
			<div class="btn btn-dark col-md-4 p-2 m-2" onclick="finalizar();pause()">Finalizar Estudo</div>
			
		</div>
	</div>
      <form id="formulario" action="/cadastra_registro" method="post">
      	
      </form>

</div>
