
<div class="container p-3">
	<a href="/estudar" class="btn btn-danger">Estudar Agora!!</a>
	<div class="row">
		<div class="col-md-4">
			<div>
				FOTO PERFIL
			</div>
			<div>
				Nome
			</div>
			<div>
				Horas estudadas na semana:
			</div>
			<div>
				Horas estudadas no mês
			</div>
		</div>
       
         
          
		
		<div class="col-md-8">
			<h4>Suas notas</h4>
			<?php foreach($this->notas as $key => $value){?>
			<div class="col-md-12 p-3">
				<?= $value["data"] ?>
				<h6> <a href="">Ver Nota: <?= $value["titulo"] ?> </a></h6>
			</div>
		<?php }?>
		</div>
			
	

	</div>
</div>