<?php  ?>
<!DOCTYPE html>
<html>
<head>
	<title>App - Tempo de Estudos</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
	<script src="js/index.js">
	</script>

</head>

<body>
<nav class="bg-info text-light p-2">
	<div class="text-center">
	  <h2><a href="/">App - Tempo estudo</a></h2>
	</div>
	<div class="container">
		<div class="row">
	<?php if(isset($_SESSION['name'])){?>
          <h3 class="col-md-8">Olá <?= $_SESSION['name']?> - Suas horas estudadas: <?= $_SESSION['total_hora'] ?></h3>
          <a class="btn btn-danger col-md-2" href="/fecha_sessao">sair</a>
          <a href="/painel_usuario" class="col-md-4 btn btn-primary">Seu painel</a>
	  <?php }?>
		</div>
	</div>
	 
</nav>

<?php 
  

?>

</body>
</html>