<?php  ?>
<!DOCTYPE html>
<html>
<head>
	<title>App - Tempo de Estudos</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<script src="js/index.js">
	</script>

</head>

<body>
<nav class="bg-info text-light p-2">
	<div class="text-center">
	  <h2><a href="/">App - Tempo estudo</a></h2>
	</div>
	<div class="container">
		<div class="row">
	<?php if(isset($_SESSION['name'])){?>
          <h3 class="col-md-8">Olá <?= $_SESSION['name']?> - Suas horas estudadas: <?= $_SESSION['total_hora'] ?></h3>
          <a class="btn btn-danger col-md-2" href="/fecha_sessao">sair</a>
	  <?php }?>
		</div>
	</div>
	 
</nav>

<?php 
  

?>

</body>
</html>